# Generated by Django 3.2.7 on 2021-09-21 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20210916_1521'),
        ('checkout80035296', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Productos.producto'),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='cantMinima',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
