# Generated by Django 3.0.8 on 2021-09-21 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout_1098730480', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
