# Generated by Django 3.2.7 on 2021-09-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout1101756167', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infoenvio',
            old_name='carrtio',
            new_name='carrito',
        ),
    ]
