# Generated by Django 3.2.7 on 2021-09-21 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Productos', '0002_auto_20210916_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoCompras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descuento', models.FloatField(blank=True, max_length=7, null=True)),
                ('CantMinima', models.IntegerField(blank=True, max_length=7, null=True)),
                ('pagado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='InfoEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('apellido', models.CharField(blank=True, max_length=300, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('pais', models.CharField(blank=True, max_length=300, null=True)),
                ('departamento', models.CharField(blank=True, max_length=300, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=300, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheackout1130619212.carritocompras')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, max_length=7, null=True)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheackout1130619212.carritocompras')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
    ]
