# Generated by Django 3.2.7 on 2021-09-21 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20210916_1521'),
        ('Checkout_1095834454', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.producto'),
        ),
    ]
