# Generated by Django 3.0.8 on 2021-09-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0002_auto_20210916_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
