# Generated by Django 3.0.8 on 2021-09-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_producto_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(default='', max_length=100),
        ),
    ]
