# Generated by Django 3.2.7 on 2021-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout_72186587', '0002_alter_carritocompras_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompras',
            name='cantMinima',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='carritocompras',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
    ]
