# Generated by Django 3.2.7 on 2021-09-21 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Checkout_79495131', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritocompra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
