# Generated by Django 3.2.7 on 2021-09-21 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout31', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='carriro',
            new_name='carrito',
        ),
        migrations.RenameField(
            model_name='info_envio',
            old_name='carriro',
            new_name='carrito',
        ),
    ]
