# Generated by Django 3.2.7 on 2021-09-22 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout31', '0002_auto_20210920_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrito_compras',
            old_name='cantminina',
            new_name='cantminima',
        ),
    ]
